### ISSUE TITLE
Setting up with my server

### ISSUE THREAD

**Issue by FurryDaniel** [sentanos/ProxyService#5]
How I can make it my server?
And it give errors 

assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Missing ACCESS_KEY
    at Object.<anonymous> (/home/danny/server/ProxyService/server.js:47:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Where do I need put access key it in server.js?
I don't need use heroku has limited hours. Running of time I can't get it webhook. Please I need help with setup my server.
Actually I hate other website hosting and limited rate I wouldn't recommend use other website. I can use domain or my ip address public if it is test with server.

**Comment by FurryDaniel** [comment]
Running out of time. They're panic and worrying. My bad English sorry.
